<?php

namespace gueye\blogBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class BlogController__JMSInjector
{
    public static function inject($container) {
        $instance = new \gueye\blogBundle\Controller\BlogController();
        return $instance;
    }
}
