parameters:
#    gueye_user.example.class: gueye\UserBundle\Example

services:
#    gueye_user.example:
#        class: %gueye_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
